### ISSUE TITLE
Integrate portions of DataTables API

### ISSUE THREAD

**Issue by lisawilliams** [squad-three/squad-three-back-end#15]
Filing this issue mainly to associate it with a wiki branch on this topic. 

The jQuery plugin we are using, DataTables, has its own API. We need to review the API documentation and understand how this will interact with the controller we will right for our bucket-list-item controller.

**Comment by lisawilliams** [comment]
Beginning of work over here: https://github.com/squad-three/squad-three-back-end/wiki/data-tables-api

**Comment by EricLScace** [comment]
Closing this issue. The DataTables API is local to the front-end browser client only. Javascript on that client can interrogate or manipulate the table locally. This doesn't affect the server until DT sends a message to the server (which is a separate interface).
